<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Report_profiling_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->status_call_id	= 'ID';
		$this->status_call_id_reason	= 'ID_REASON';
		$this->status_call_nama_reason	= 'NAMA_REASON';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_id_reason	= 'id_reason';
		$this->f_nama_reason	= 'nama_reason';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->status_call_id,
			$this->f_id_reason	=> $this->status_call_id_reason,
			$this->f_nama_reason	=> $this->status_call_nama_reason,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-12 19:58:23 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

