<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_absensi_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_absensi_id	= 'ID';
		$this->t_absensi_nama	= 'NAMA';
		$this->t_absensi_nik	= 'NIK';
		$this->t_absensi_stts	= 'STATUS';
		$this->t_absensi_waktu_in	= 'DATE';
		$this->t_absensi_picture	= 'PICTURE';
		$this->t_absensi_update_by	= 'UPDATE_BY';
		$this->t_absensi_latitude	= 'LATITUDE';
		$this->t_absensi_longitude	= 'LONGITUDE';
		$this->t_absensi_agentid	= 'AGENTID';
		$this->nikagent_id	= 'NIKAGENT_ID';
		$this->nikagent_nmuser	= 'NMUSER';
		$this->nikagent_passuser	= 'PASSUSER';
		$this->nikagent_opt_level	= 'OPT_LEVEL';
		$this->nikagent_opt_status	= 'OPT_STATUS';
		$this->nikagent_picture	= 'NIKAGENT_PICTURE';
		$this->nikagent_nama	= 'NIKAGENT_NAMA';
		$this->nikagent_agentid	= 'NIKAGENT_AGENTID';
		$this->nikagent_kategori	= 'KATEGORI';
		$this->nikagent_tl	= 'TL';
		$this->nikagent_nik_absensi	= 'NIK_ABSENSI';
		$this->statusagent_id	= 'STATUSAGENT_ID';
		$this->statusagent_keterangan	= 'KETERANGAN';
		$this->statusagent_kode	= 'KODE';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nama	= 'nama';
		$this->f_nik	= 'nik';
		$this->f_stts	= 'stts';
		$this->f_waktu_in	= 'waktu_in';
		$this->f_picture	= 'picture';
		$this->f_update_by	= 'update_by';
		$this->f_latitude	= 'latitude';
		$this->f_longitude	= 'longitude';
		$this->f_agentid	= 'agentid';
		$this->f_nikagent_id	= 'nikagent_id';
		$this->f_nmuser	= 'nmuser';
		$this->f_passuser	= 'passuser';
		$this->f_opt_level	= 'opt_level';
		$this->f_opt_status	= 'opt_status';
		$this->f_nikagent_picture	= 'nikagent_picture';
		$this->f_nikagent_nama	= 'nikagent_nama';
		$this->f_nikagent_agentid	= 'nikagent_agentid';
		$this->f_kategori	= 'kategori';
		$this->f_tl	= 'tl';
		$this->f_nik_absensi	= 'nik_absensi';
		$this->f_statusagent_id	= 'statusagent_id';
		$this->f_keterangan	= 'keterangan';
		$this->f_kode	= 'kode';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_absensi_id,
			$this->f_nama	=> $this->t_absensi_nama,
			$this->f_agentid	=> $this->t_absensi_agentid,
			$this->f_nik	=> $this->t_absensi_nik,
			$this->f_stts	=> $this->t_absensi_stts,
			$this->f_waktu_in	=> $this->t_absensi_waktu_in,
			$this->f_kategori	=> $this->nikagent_kategori,
			$this->f_tl	=> $this->nikagent_tl,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-04-01 09:25:43 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

