<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Input_absen_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->absen_id	= 'id';
		$this->absen_nik	= 'NIK';
		$this->absen_nama	= 'Nama';
		$this->absen_stts	= 'Status';	
		$this->absen_waktu_in	= 'Waktu In';	

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nama = 'nama';
		$this->f_nik = 'nik';
		$this->f_stts	= 'stts';
		$this->f_waktu_in	= 'waktu_in';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->absen_id,
			$this->f_nama => $this->absen_nama,
			$this->f_nik => $this->absen_nik,
			$this->f_stts => $this->absen_stts,
			$this->f_waktu_in => $this->absen_waktu_in

		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-12 19:58:23 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

