<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agent_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			sys_user.id as id,
			sys_user.nmuser as nmuser,
			sys_user.passuser as passuser,
			sys_user.opt_level as opt_level,
			sys_user.opt_status as opt_status,
			sys_user.picture as picture,
			sys_user.nama as nama,
			sys_user.agentid as agentid,
			sys_user.kategori as kategori,
			Level.id as Level_id,
			Level.nmlevel as nmlevel,
			Level.opt_status as Level_opt_status,
			Status.id as Status_id,
			Status.status as status,
			optstatus.id as optstatus_id,
			optstatus.status as optstatus_status,
			sys_user.tl as tl,
		');
		
		$this->datatables->from('sys_user');
		$this->db->where('sys_user.opt_level', 8);
		$this->datatables->join('sys_level Level','Level.id=sys_user.opt_level','LEFT'); 
	
		$this->datatables->join('sys_status Status','Status.id=sys_user.opt_status','LEFT'); 
	
		$this->datatables->join('sys_status optstatus','optstatus.id=Level.opt_status','LEFT'); 

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'sys_user.id as id',
			'sys_user.nmuser as nmuser',
			'sys_user.passuser as passuser',
			'sys_user.opt_level as opt_level',
			'sys_user.opt_status as opt_status',
			'sys_user.picture as picture',
			'sys_user.nama as nama',
			'sys_user.agentid as agentid',
			'sys_user.kategori as kategori',
			'Level.id as Level_id',
			'Level.nmlevel as nmlevel',
			'Level.opt_status as Level_opt_status',
			'Status.id as Status_id',
			'Status.status as status',
			'optstatus.id as optstatus_id',
			'optstatus.status as optstatus_status',
			'sys_user.tl as tl',
		
		);
		$this->db->select($afield);
		$this->db->where('sys_user.opt_level', 8);
		$this->db->join('sys_level Level','Level.id=sys_user.opt_level','LEFT'); 
		$this->db->join('sys_status Status','Status.id=sys_user.opt_status','LEFT'); 
		$this->db->join('sys_status optstatus','optstatus.id=Level.opt_status','LEFT'); 

		$this->db->order_by('sys_user.id', 'ASC');
		return $this->db->get('sys_user')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'sys_user.id as id',
			'sys_user.nmuser as nmuser',
			'sys_user.passuser as passuser',
			'sys_user.opt_level as opt_level',
			'sys_user.opt_status as opt_status',
			'sys_user.picture as picture',
			'sys_user.nama as nama',
			'sys_user.agentid as agentid',
			'sys_user.kategori as kategori',
			'Level.id as Level_id',
			'Level.nmlevel as nmlevel',
			'Level.opt_status as Level_opt_status',
			'Status.id as Status_id',
			'Status.status as status',
			'optstatus.id as optstatus_id',
			'optstatus.status as optstatus_status',
			'sys_user.tl as tl',
		
		);
		$this->db->select($afield);
		$this->db->join('sys_level Level','Level.id=sys_user.opt_level','LEFT'); 
		$this->db->join('sys_status Status','Status.id=sys_user.opt_status','LEFT'); 
		$this->db->join('sys_status optstatus','optstatus.id=Level.opt_status','LEFT'); 

		$this->db->where('sys_user.id', $id);
		$this->db->order_by('sys_user.id', 'ASC');
		return $this->db->get('sys_user')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('sys_user.id <>',$id);

		$q = $this->db->get_where('sys_user', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('sys_user', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('sys_user.id', $id);
		$this->db->update('sys_user', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('sys_user.id',$data);	
	
			$this->db->delete('sys_user');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-30 09:24:57 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
