<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agent_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_user_id	= 'ID';
		$this->sys_user_nmuser	= 'NMUSER';
		$this->sys_user_passuser	= 'PASSUSER';
		$this->sys_user_opt_level	= 'OPT_LEVEL';
		$this->sys_user_opt_status	= 'OPT_STATUS';
		$this->sys_user_picture	= 'PICTURE';
		$this->sys_user_nama	= 'NAMA';
		$this->sys_user_agentid	= 'AGENTID';
		$this->sys_user_kategori	= 'KATEGORI';
		$this->Level_id	= 'LEVEL_ID';
		$this->Level_nmlevel	= 'NMLEVEL';
		$this->Level_opt_status	= 'LEVEL_OPT_STATUS';
		$this->Status_id	= 'STATUS_ID';
		$this->Status_status	= 'STATUS';
		$this->optstatus_id	= 'OPTSTATUS_ID';
		$this->optstatus_status	= 'OPTSTATUS_STATUS';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nmuser	= 'nmuser';
		$this->f_passuser	= 'passuser';
		$this->f_opt_level	= 'opt_level';
		$this->f_opt_status	= 'opt_status';
		$this->f_picture	= 'picture';
		$this->f_nama	= 'nama';
		$this->f_agentid	= 'agentid';
		$this->f_kategori	= 'kategori';
		$this->f_Level_id	= 'Level_id';
		$this->f_nmlevel	= 'nmlevel';
		$this->f_Level_opt_status	= 'Level_opt_status';
		$this->f_Status_id	= 'Status_id';
		$this->f_status	= 'status';
		$this->f_optstatus_id	= 'optstatus_id';
		$this->f_optstatus_status	= 'optstatus_status';
		$this->f_tl	= 'tl';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_nmuser	=> $this->sys_user_nmuser,
			$this->f_nama	=> $this->sys_user_nama,
			$this->f_agentid	=> $this->sys_user_agentid,
			// $this->f_kategori	=> $this->sys_user_kategori,
			// $this->f_nmlevel	=> $this->Level_nmlevel,
			// $this->f_status	=> $this->Status_status,
			$this->f_tl	=> $this->tl,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-30 09:24:57 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

