<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Status_call_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			status_call.id as id,
			status_call.id_reason as id_reason,
			status_call.nama_reason as nama_reason,
		');
		
		$this->datatables->from('status_call');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'status_call.id as id',
			'status_call.id_reason as id_reason',
			'status_call.nama_reason as nama_reason',
		
		);
		$this->db->select($afield);

		$this->db->order_by('status_call.id', 'ASC');
		return $this->db->get('status_call')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'status_call.id as id',
			'status_call.id_reason as id_reason',
			'status_call.nama_reason as nama_reason',
		
		);
		$this->db->select($afield);

		$this->db->where('status_call.id', $id);
		$this->db->order_by('status_call.id', 'ASC');
		return $this->db->get('status_call')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('status_call.id <>',$id);

		$q = $this->db->get_where('status_call', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('status_call', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('status_call.id', $id);
		$this->db->update('status_call', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('status_call.id',$data);	
	
			$this->db->delete('status_call');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-12 19:58:23 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
