<?php
require APPPATH. '/controllers/ebs_indihome/Ebs_indihome_config.php';

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ebs_indihome extends CI_Controller {
   private $log_key,$log_temp,$title;
   function __construct(){
        parent::__construct();
		// $this->load->model('Ebs_indihome/Ebs_indihome_model','tmodel');
		$this->log_key ='log_Ebs_indihome';
		$this->title = new Ebs_indihome_config();
		$this->load->model('Custom_model/Indihome_model');
   }


	public function index(){
		
		$data = array(
			'title_page_big'		=> 'EBS Indihome',
			'title'					=> $this->title,
			'link_refresh_table'	=> site_url().'Ebs_indihome/Ebs_indihome/refresh_table/'.$this->_token,
			'link_create'			=> site_url().'Ebs_indihome/Ebs_indihome/create',
			'link_update'			=> site_url().'Ebs_indihome/Ebs_indihome/update',
			'link_delete'			=> site_url().'Ebs_indihome/Ebs_indihome/delete_multiple',
		);
		
		$this->template->load('Ebs_indihome/Ebs_indihome_list',$data);
		
		/*
		$data = array();
		if (isset($_GET["svcnumber"])) {
			$data["svcnumber"] = $_GET["svcnumber"];
		}
		$this->load->view('Ebs_indihome/Ebs_indihome_form', $data);
		*/
	}

	public function get_data_list()
	{
		$data = array();
		$this->load->view('Ebs_indihome/Ebs_indihome_datatable', $data);
	}
	public function get_form()
	{
		$data = array();
		$data['selectedtable'] = $_GET['datanya'];
		var_dump($_GET['datanya']);
		$this->load->view('Ebs_indihome/Ebs_indihome_formebs', $data);
	}

	public function send()
	{
		$url = "http://10.60.175.132/dev_bill/app/manual_indihome.php?group_id=9014006130523&nper=202104&email=agusafrilusputra@gmail.com&emailcc=&upd=rial&_=1617820915141";
		$curlHandle = curl_init(); 
		  // init curl
		curl_setopt($curlHandle, CURLOPT_URL, $url); // set the url to fetch
		curl_setopt($curlHandle, CURLOPT_HEADER, 0);
		curl_setopt($curlHandle, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($curlHandle, CURLOPT_TIMEOUT,30);
		curl_setopt($curlHandle, CURLOPT_POST, 0);
		$content = curl_exec($curlHandle);
		curl_close($curlHandle);
		//return $content;
		//$rest = json_encode($content,true);
		echo $content;
	}

	public function get_data($no=null){
		//$no = '131184160013';
		$url = "http://10.60.175.132/ideas_new/app/data/grid/ebs_indihome_new.php?action=search&telp=$no";
		$curlHandle = curl_init(); 
		  // init curl
		curl_setopt($curlHandle, CURLOPT_URL, $url); // set the url to fetch
		curl_setopt($curlHandle, CURLOPT_HEADER, 0);
		curl_setopt($curlHandle, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($curlHandle, CURLOPT_TIMEOUT,30);
		curl_setopt($curlHandle, CURLOPT_POST, 0);
		$content = curl_exec($curlHandle);
		curl_close($curlHandle);
		//return $content;
		//$rest = json_encode($content,true);
		echo $content;
	}

	public function preview(){
		//$no = '131184160013';
		$url = "http://10.60.175.132/dev_bill/app/prev_indihome.php?group_id=9014006130523&nper=202104";
		$curlHandle = curl_init(); 
		  // init curl
		curl_setopt($curlHandle, CURLOPT_URL, $url); // set the url to fetch
		curl_setopt($curlHandle, CURLOPT_HEADER, 0);
		curl_setopt($curlHandle, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($curlHandle, CURLOPT_TIMEOUT,30);
		curl_setopt($curlHandle, CURLOPT_POST, 0);
		$content = curl_exec($curlHandle);
		curl_close($curlHandle);
		//return $content;
		//$rest = json_encode($content,true);
		echo $content;
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-11-09 06:32:14 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

