<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Leader_on_duty_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			leader_on_duty.id as id,
			leader_on_duty.agentid as agentid,
			leader_on_duty.tanggal as tanggal,
			leader_on_duty.gelombang as gelombang,
		');
		
		$this->datatables->from('leader_on_duty');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'leader_on_duty.id as id',
			'leader_on_duty.agentid as agentid',
			'leader_on_duty.tanggal as tanggal',
			'leader_on_duty.gelombang as gelombang',
		
		);
		$this->db->select($afield);

		$this->db->order_by('leader_on_duty.id', 'ASC');
		return $this->db->get('leader_on_duty')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'leader_on_duty.id as id',
			'leader_on_duty.agentid as agentid',
			'leader_on_duty.tanggal as tanggal',
			'leader_on_duty.gelombang as gelombang',
		
		);
		$this->db->select($afield);

		$this->db->where('leader_on_duty.id', $id);
		$this->db->order_by('leader_on_duty.id', 'ASC');
		return $this->db->get('leader_on_duty')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('leader_on_duty.id <>',$id);

		$q = $this->db->get_where('leader_on_duty', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('leader_on_duty', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('leader_on_duty.id', $id);
		$this->db->update('leader_on_duty', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('leader_on_duty.id',$data);	
	
			$this->db->delete('leader_on_duty');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-31 15:28:46 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
