<?php
require APPPATH. '/controllers/Ebs_nonpots/Ebs_nonpots_config.php';

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ebs_nonpots extends CI_Controller {
   private $log_key,$log_temp,$title;
   function __construct(){
        parent::__construct();
		// $this->load->model('Ebs_nonpots/Ebs_nonpots_model','tmodel');
		$this->log_key ='log_Ebs_nonpots';
		$this->title = new Ebs_nonpots_config();
   }


	public function index(){
		$data = array(
			'title_page_big'		=> 'EBS Non Pots',
			'title'					=> $this->title,
			'link_refresh_table'	=> site_url().'Ebs_nonpots/Ebs_nonpots/refresh_table/'.$this->_token,
			'link_create'			=> site_url().'Ebs_nonpots/Ebs_nonpots/create',
			'link_update'			=> site_url().'Ebs_nonpots/Ebs_nonpots/update',
			'link_delete'			=> site_url().'Ebs_nonpots/Ebs_nonpots/delete_multiple',
		);
		
		$this->template->load('Ebs_nonpots/Ebs_nonpots_list',$data);
	}	

	



};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-11-09 06:32:14 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

